# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tukiogram', '0003_auto_20170312_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tukio',
            name='desc',
            field=models.CharField(max_length=70),
        ),
    ]
